### ISSUE TITLE
Realizar validación con 5 usuarios

### ISSUE THREAD

**Issue by Margarita2020-prog** [Margarita2020-prog/Equipo7_SJBS_PPI2020#19]

**Comment by fernandamc22** [comment]
eso no le tocaba a julian? yo estoy encargandome de los cuadros

**Comment by Margarita2020-prog** [comment]
El del primer cuadrante le tocaba a Julián y el no lo hizo, así que lo realizo Kevin, ya estamos en el segundo cuadrante y toca hacer otras validaciones, entonces te lo puse a ti
