### ISSUE TITLE
2. Modelo Entidad-Relación

### ISSUE THREAD

**Issue by Margarita2020-prog** [Margarita2020-prog/Equipo7_SJBS_PPI2020#25]

**Comment by jennymontoya1001** [comment]
@fernandamc22  @Ceferovic se revisa la wiki y no se evidencia avance en esta actividad.

**Comment by jennymontoya1001** [comment]
@Margarita2020-prog no se evidencia avance de esta actividad

**Comment by Margarita2020-prog** [comment]
@jennymontoya1001 ,Ya subí el desarrollo de la actividad 2, el modelo entidad relación

**Comment by Margarita2020-prog** [comment]
@jennymontoya1001 , Ya subí el desarrollo de la actividad 4, el modelo lógico
