### ISSUE TITLE
5. Construcción de la BD haciendo uso de MySQL

### ISSUE THREAD

**Issue by Margarita2020-prog** [Margarita2020-prog/Equipo7_SJBS_PPI2020#28]

**Comment by jennymontoya1001** [comment]
@fernandamc22 @Ceferovic se revisa la wiki y no se evidencia avance en esta actividad.

**Comment by jennymontoya1001** [comment]
@Ceferovic no se evidencia avance de esta actividad

**Comment by Ceferovic** [comment]
@jennymontoya1001 El archivo sql ha sido montado al repositorio

**Comment by Ceferovic** [comment]
@jennymontoya1001 Se ha subido el archivo de la base de datos
